version: "3"

services:
  carbon-back:
    user: node
    build:
      context: carbon-back
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./carbon-back:/home/node
    command: sh -c "npm install && npm run start:dev"