version: "3"

services:

  carbon-app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - './app:/app'
      - '${PWD}/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
        - front

  carbon-back:
    user: node
    build:
      context: carbon-back
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./carbon-back:/home/node
    command: sh -c "npm install && npm run start:dev"
    networks:
        - front
        - back
    ports:
      - "3000:3000"

  carbon-db:
    image: mysql:8.0.33
    environment:
      MYSQL_DATABASE: carbon
      MYSQL_USER: carbon
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./db/carbon:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - back

networks:
  front:
    driver: bridge
  back:
    driver: bridge